const presets = [
  {
    particleSpeed: 3,
    particleCount: 200,
    connectionDistance: 100,
    connectionStroke: 50,
    connectionHue: 0,
    particleHue: 50,
    showParticles: true,
    animateConnectionHue: false,
    connectionMode: 1,
  },
  {
    particleSpeed: 2,
    particleCount: 800,
    connectionDistance: 50,
    connectionHue: 230,
    showParticles: false,
    animateConnectionHue: true,
    connectionMode: 2,
  },
  {
    particleSpeed: 1,
    particleCount: 50,
    connectionDistance: 300,
    showParticles: false,
    animateConnectionHue: true,
    connectionMode: 1,
  },
  {
    particleSpeed: 3,
    particleCount: 800,
    connectionDistance: 30,
    connectionStroke: 255,
    connectionHue: 300,
    particleHue: 100,
    showParticles: true,
    animateConnectionHue: false,
  },
  {
    particleSpeed: 1,
    particleCount: 40,
    connectionDistance: 300,
    connectionStroke: 255,
    connectionHue: 0,
    showParticles: false,
    animateConnectionHue: false,
    connectionMode: 1,
  },
  {
    particleSpeed: 1,
    particleCount: 600,
    connectionDistance: 80,
    connectionStroke: 10,
    connectionHue: 0,
    particleHue: 360,
    showParticles: true,
    animateConnectionHue: false,
  },
];