const presets = [
  { // 1
    particleSpeed: 3,
    particleCount: 200,
    connectionDistance: 100,
    connectionStroke: 50,
    connectionHue: 0,
    particleHue: 50,
    showParticles: true,
    animateConnectionHue: false,
    connectionMode: 1,
    reactToAudio: true,
  },
  { // 2
    particleSpeed: 2,
    particleCount: 800,
    connectionDistance: 50,
    connectionHue: 230,
    showParticles: false,
    animateConnectionHue: true,
    connectionMode: 2,
    reactToAudio: true,
  },
  { // 3
    particleSpeed: 1,
    particleCount: 50,
    connectionDistance: 300,
    showParticles: false,
    animateConnectionHue: true,
    connectionMode: 1,
    reactToAudio: true,
  },
  { // 4
    particleSpeed: 3,
    particleCount: 800,
    connectionDistance: 30,
    connectionStroke: 255,
    connectionHue: 300,
    particleHue: 100,
    showParticles: true,
    animateConnectionHue: false,
    reactToAudio: true,
  },
  { // 5
    particleSpeed: 1,
    particleCount: 40,
    connectionDistance: 300,
    connectionStroke: 255,
    connectionHue: 0,
    showParticles: false,
    animateConnectionHue: false,
    connectionMode: 1,
    reactToAudio: true,
  },
  { // 6
    particleSpeed: 1,
    particleCount: 600,
    connectionDistance: 80,
    connectionStroke: 15,
    connectionHue: 0,
    particleHue: 360,
    showParticles: true,
    animateConnectionHue: false,
    reactToAudio: true,
  },
  { // 7
    particleSpeed: 1,
    particleCount: 50,
    connectionDistance: 300,
    showParticles: false,
    animateConnectionHue: true,
    connectionMode: 1,
    reactToAudio: false,
  },
  { // 8
    particleSpeed: 2,
    particleCount: 200,
    connectionDistance: 100,
    connectionStroke: 50,
    connectionHue: 0,
    particleHue: 200,
    showParticles: true,
    animateConnectionHue: false,
    connectionMode: 1,
    reactToAudio: false,
  },
  { // 9
    particleSpeed: 0.5,
    particleCount: 800,
    connectionDistance: 0,
    connectionStroke: 50,
    connectionHue: 0,
    particleHue: 40,
    showParticles: true,
    animateConnectionHue: false,
    connectionMode: 1,
    reactToAudio: false,
  },
];