const presets = [

  {
    n: 1,
    d: 49,
    zScale: 1,
    showRose: true,
    showMaurerRose: true,
    popOut: false,
    fill: false,
    triangleStrip: false,
    oscillateN: false,
    oscillateD: false,
  },
  {
    n: 2,
    d: 23,
    zScale: 0.5,
    showRose: true,
    showMaurerRose: true,
    popOut: false,
    fill: false,
    triangleStrip: false,
    oscillateN: false,
    oscillateD: false,
  },
  {
    n: 10,
    d: 239,
    zScale: 1,
    showRose: false,
    showMaurerRose: true,
    popOut: false,
    fill: true,
    triangleStrip: true,
    oscillateN: false,
    oscillateD: false,
  },
  {
    n: 10,
    d: 239,
    zScale: 1,
    showRose: false,
    showMaurerRose: true,
    popOut: true,
    fill: true,
    triangleStrip: true,
    oscillateN: false,
    oscillateD: false,
  },
  {
    n: 21,
    d: 14,
    zScale: 1,
    showRose: false,
    showMaurerRose: true,
    popOut: false,
    fill: true,
    triangleStrip: true,
    oscillateN: false,
    oscillateD: false,
  },
  {
    n: 1,
    d: 42,
    zScale: 1,
    showRose: false,
    showMaurerRose: true,
    popOut: false,
    fill: true,
    triangleStrip: true,
    oscillateN: false,
    oscillateD: false,
  },
  {
    n: 4,
    d: 134,
    zScale: 1,
    showRose: false,
    showMaurerRose: true,
    popOut: false,
    fill: true,
    triangleStrip: true,
    oscillateN: false,
    oscillateD: false,
  },
  {
    n: 5,
    d: 119,
    zScale: 1,
    showRose: false,
    showMaurerRose: true,
    popOut: false,
    fill: true,
    triangleStrip: true,
    oscillateN: false,
    oscillateD: false,
  },
  {
    zScale: 1,
    showRose: false,
    showMaurerRose: true,
    popOut: false,
    fill: true,
    triangleStrip: true,
    oscillateN: true,
    oscillateD: true,
  },
  {
    zScale: 1,
    showRose: false,
    showMaurerRose: true,
    popOut: true,
    fill: true,
    triangleStrip: true,
    oscillateN: true,
    oscillateD: true,
  },
];